[tools]
# Cloud & Infrastructure
awscli = "latest"
gcloud = "latest"
terraform = "latest"
terraform-docs = "latest"
terraformer = "latest"
terragrunt = "latest"
tfstate-lookup = "latest"
vault = "latest"

# Container & Kubernetes
ctop = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"

# Development Languages & Runtimes
crystal = "latest"
deno = "latest"
go = "latest"
ruby = "latest"
rust = "latest"

# Development Tools
bat = "latest"
direnv = "latest"
neovim = "latest"

# Git & Version Control
"cargo:cocogitto" = "latest"
gh = "latest"
glab = "latest"
"go:github.com/CtrlSpice/otel-desktop-viewer" = "latest"
"go:github.com/equinix-labs/otel-cli" = "latest"
hk = "latest"
node = "latest"
pdm = "latest"
pipx = "latest"
"pipx:black" = "latest"
"pipx:check-jsonschema" = "latest"
"pipx:mkdocs" = "latest"
"pipx:mypy" = "latest"
"pipx:pirate-get" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pytest" = "latest"
"pipx:ruff" = "latest"
"pipx:yq" = "latest"
"cargo:atuin" = "latest"
kind = "latest"
prettier = "latest"
"cargo:zoxide" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:xh" = "latest"
"npm:fx" = "latest"
krew = "latest"

[settings]
experimental = true
