# Language runtimes and interpreters
[tools]
# crystal = "latest"  # plugin broken: list-all exits with code 1
deno = "2.6.10"
go = "1.26.0"
ruby = "4.0.1"
rust = "1.93.1"
scala = "3.8.1"
bun = "1.3.9"
erlang = "28.3.2"
elixir = "1.19.5-otp-28"
uv = "0.10.4"
