# Git & Version Control tools
[tools]
gh = "2.87.3"
glab = "1.86.0"
hk = "1.36.0"

# Conventional commits
"cargo:cocogitto" = "6.5.0"

"cargo:git-delta" = "0.18.2"
"go:github.com/github/git-sizer" = "1.5.0"

"cargo:gitui" = "0.28.0"
"cargo:gitoxide" = "0.51.0"
