# Offensive tools to install
[tools]
"go:github.com/antonmedv/fx" = "latest"
"go:github.com/ffuf/ffuf" = "1.5.0"
"go:github.com/glitchedgitz/cook/v2/cmd/cook" = "2.2.1"
"go:github.com/lc/gau/v2/cmd/gau" = "2.2.4"
"go:github.com/projectdiscovery/pdtm/cmd/pdtm" = "0.1.3"
"go:github.com/sw33tLie/sns" = "latest"
"go:github.com/x90skysn3k/brutespray" = "latest"
"go:github.com/xm1k3/cent" = "1.3.4"
"go:github.com/tomnomnom/waybackurls" = "0.1.0"

# --- Network tools ---
"go:github.com/projectdiscovery/httpx/cmd/httpx" = "1.8.1"
"go:github.com/projectdiscovery/subfinder/v2/cmd/subfinder" = "2.12.0"
"go:github.com/projectdiscovery/shuffledns/cmd/shuffledns" = "1.2.1"
"go:github.com/projectdiscovery/mapcidr/cmd/mapcidr" = "1.1.97"
"go:github.com/projectdiscovery/dnsx/cmd/dnsx" = "1.2.3"

"go:github.com/projectdiscovery/nuclei/v3/cmd/nuclei" = "3.7.0"
"go:github.com/projectdiscovery/interactsh/cmd/interactsh-client" = "1.3.0"
